# SPDX-License-Identifier: GPL-2.0-only OR GPL-3.0-only
# Copyright (c) 2025 Gavin Henry <ghenry@antnetworks.com>
version: 2
updates:
  - package-ecosystem: cargo
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
    target-branch: main