# SPDX-License-Identifier: GPL-3.0-only
# Copyright (c) 2025 Gavin Henry <ghenry@antnetworks.com>
name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Install Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        components: clippy, rustfmt
        profile: minimal
        override: true

    - name: Format check
      run: cargo fmt -- --check

    - name: Clippy check
      run: cargo clippy --all-targets --all-features -- -D warnings

    - name: Run tests
      run: cargo test

